---
- name: Install  build-essential for Debian OS family
  apt: name=build-essential
  tags: ["packages","vagrant"]
  
- name: Install Ruby packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: False
  with_flattened:
    - ruby_base_packages[ruby_version]
    - ruby_dev_packages[ruby_version]
    - ruby_gems_integration_packages[ruby_gems_integration]
    - ruby_packages
    - ruby_group_packages
    - ruby_host_packages
    - ruby_dependent_packages

- name: Check what gems are installed
  command: gem list --local --no-verbose --no-versions
  register: ruby_register_installed_gems
  changed_when: False
  when: ((ruby_default_gems is defined and ruby_default_gems) or
         (ruby_gems is defined and ruby_gems) or
         (ruby_group_gems is defined and ruby_group_gems) or
         (ruby_host_gems is defined and ruby_host_gems) or
         (ruby_dependent_gems is defined and ruby_dependent_gems))

- name: Install specified gems from RubyGems
  command: gem install --no-verbose --conservative {{ item }}
  with_flattened:
    - ruby_default_gems
    - ruby_gems
    - ruby_group_gems
    - ruby_host_gems
    - ruby_dependent_gems
  when: ((ruby_register_installed_gems is defined and ruby_register_installed_gems) and
         (item not in ruby_register_installed_gems.stdout_lines))

